name: ecdsa-wasm
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: LavaMoat/ecdsa-wasm
  name: ecdsa-wasm
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
