[package]
name = "mpc-websocket"
version = "0.2.0"
edition = "2018"
default-run = "mpc-websocket"

[dependencies]
thiserror = "1"
warp = "0.3"
log = "0.4"
pretty_env_logger = "0.4"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1"
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
structopt = "0.3"
uuid = { version = "0.8", features = ["v4"] }
json-rpc2 = { version = "0.11", features = ["async"] }
async-trait = "0.1"

[[bin]]
name = "mpc-websocket"
path = "src/bin/main.rs"

[profile.release]
strip = true
