[package]
name = "ecdsa-wasm-server"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1"
warp = "0.3"
log = "0.4"
pretty_env_logger = "0.4"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
futures-util = "0.3"
