[package]
name = "mpc-snap-wasm"
version = "0.1.0"
edition = "2018"
license = "MIT"
description = "Webassembly utilities for the threshold signatures snap"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.6"
wasm-bindgen = { version = "0.2.79", features = ["serde-serialize"] }
#serde = {version = "1", features = ["derive"]}
