name: Common

on: [pull_request]

env:
  RUST_LOG: "0"
  WORKING_DIRECTORY: ./common

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt
      - name: Run cargo fmt
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: cargo fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy
      - name: Run cargo clippy
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: cargo clippy --all

  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Run cargo build
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: cargo check

  check-wasm:
    name: check-wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown
      - name: Run cargo build
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: cargo check --target wasm32-unknown-unknown
