name: Server

on: [pull_request]

env:
  CI: 1
  CARGO_INCREMENTAL: 0
  RUST_LOG: "debug"

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    env:
      RUST_LOG: "0"
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt
      - name: Run cargo fmt
        run: cd server && cargo fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    env:
      RUST_LOG: "0"
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy
      - name: Run cargo clippy
        run: cd server && cargo clippy --all

  build:
    name: build
    runs-on: ubuntu-latest
    env:
      RUST_LOG: "0"
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Run cargo build
        run: cd server && cargo build --release
