name: Cargo

on: [push, pull_request]

env:
  CI: 1
  CARGO_INCREMENTAL: 0
  RUST_LOG: "debug"

jobs:
  #check-license:
    #name: Check license
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v2

      #- name: Install Rust
        #uses: actions-rs/toolchain@v1
        #with:
          #profile: minimal

      #- name: Install required tools
        #run: |
          #cargo install cargo-deny

      #- name: Check licenses
        #run: |
          #cargo deny check

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    env:
      RUST_LOG: "0"
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt
      - name: Run cargo fmt
        run: cd server && cargo fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    env:
      RUST_LOG: "0"
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy
      - name: Run cargo clippy
        run: cd server && cargo clippy --all

  #check-wasm:
    #name: check wasm32-unknown-unknown
    #runs-on: ubuntu-latest
    #env:
      #RUST_LOG: "0"
    #steps:
      #- uses: actions/checkout@v2
      #- name: Install Rust
        #uses: actions-rs/toolchain@v1
        #with:
          #profile: minimal
      #- name: Run cargo build
        #run: cargo check --target wasm32-unknown-unknown

  build:
    name: build server
    runs-on: ubuntu-latest
    env:
      RUST_LOG: "0"
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Run cargo build
        run: cd server && cargo build --release
