name: WASM

on: [pull_request]

env:
  CI: 1
  CARGO_INCREMENTAL: 0
  RUST_LOG: "debug"

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    env:
      RUST_LOG: "0"
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt
      - name: Run cargo fmt
        run: cd wasm && cargo fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    env:
      RUST_LOG: "0"
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy
          target: wasm32-unknown-unknown
      - name: Run cargo clippy
        run: cd wasm && cargo clippy --all

  check:
    name: check
    runs-on: ubuntu-latest
    env:
      RUST_LOG: "0"
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown
      - name: Run cargo build
        run: cd wasm && cargo check
